import { GetServerSideProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { User } from '../types/user';

export const getServerSideProps: GetServerSideProps<{
	users: User[];
}> = async () => {
	const request = await fetch(
		'https://jsonplaceholder.typicode.com/users'
	);
	const data = await request.json();
	return {
		props: { users: data },
	};
};
export default function Home({ users }: { users: User[] }) {
	return (
		<>
			<Head>
				<title>Router dynamic Next</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<main>
				<div className=' border rounded bg-orange-300 flex flex-col my-2'>
					<div className='py-2 px-3 text-center text-[32px] text-bold'>
						Users
					</div>
					{users.map(({ name, id }) => (
						<Link
							href={{
								pathname: name
									.toLocaleLowerCase()
									.replaceAll(/ /gi, ''),
								query: {
									userId: id,
								},
							}}
							key={name}
							className='text-[18px] py-2 px-3 hover:bg-slate-500 transition-all cur'
						>
							{name}
						</Link>
					))}
				</div>
			</main>
		</>
	);
}
